(function(g){var window=this;'use strict';var s2=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},t2=function(a){return g.ZD(a)&&a.Z("web_player_i_see_captions_3")},nIa=function(a,b){return g.D(this,function d(){var e,f;
return g.z(d,function(h){if(1==h.i)return e=a+"|"+b,g.w(h,(0,g.BE)(),2);f=h.l;return h.return(f.get("captions",e))})})},oIa=function(a,b){var c=new g.GE;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},pIa=function(a,b,c){nIa(a,b).then(function(d){d&&c(d.trackData,new g.GE(d.metadata))})},u2=function(){this.segments=[]},qIa=function(a,b){var c=g.ub(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.jb(a.segments,c),g.jb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.rb(a.segments,c,0,b),g.rb(a.segments,c+1,0,b)))},v2=function(a,b,c,d,e,f){g.F.call(this);
this.policy=a;this.player=b;this.W=c;this.G=d;this.C=e;this.V=f;this.J=this.player.T();this.B=new u2;this.l=this.u=this.i=null;this.L=new g.J(this.hH,1E3,this);this.events=new g.UL(this);g.G(this,this.L);g.G(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.AD);this.AD();this.hH()},rIa=function(a,b){var c=g.Hz(g.hA(b,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.l=g.Ap(c,d,3,100).then(function(e){a:{var f=e.xhr;a.Ga();if(a.u){var h=!(a.C?f.response:f.responseText)||400<=f.status;if(e=g.QB(f)){f=g.hA(a.u,{});h=a.u;g.Oz(h.l,f,e);h.requestId=f.get("req_id");rIa(a,a.u);break a}h||null==a.G||(e=a.u.i[0],a.C?a.G(f.response,1E3*(e.startTime+a.player.Lc())):a.G(f.responseText,1E3*(e.startTime+a.player.Lc())))}a.u=null;a.l=null}});
a.u=b;qIa(a.B,a.u.i[0].Ia)},w2=function(a,b){g.hM.call(this,b.T());
this.i=a;this.I=b;this.u=null;this.C=!1;this.G=g.bE(this.I.T())&&!this.i.isManifestless},tIa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.jM(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.xGa.get(e);null==n&&(n=sIa[e]||sIa[e.replace(/-/g,"_")],g.xGa.set(e,n));h=n||h}c.push(new g.GE({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},uIa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},vIa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.jM(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},x2=function(a){if(!wIa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(xIa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},y2=function(a,b,c,d,e,f){var h={};
g.Qa(h,b);g.Qa(h,a.params);g.Qa(h,c);var l={};g.Qa(l,b.Yc);a.params.Yc&&g.Qa(l,a.params.Yc);g.Qa(l,c.Yc);h.Yc=l;g.V.call(this,{D:"div",K:"caption-window",U:{id:"caption-window-"+a.id,dir:1===h.vf?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:h.lang},S:[{D:"span",K:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.ma=!1;this.l=a;this.xa=this.ra=null;this.playerWidth=e;this.playerHeight=f;this.G=null;this.maxWidth=.96*e;this.Ma=.96*f;this.i=h;this.ob=c;this.Aa=
b;this.B=this.Ba("captions-text");this.Za=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Ea=d/360*16;this.type=0;this.Na=this.Ea*yIa(l);a=new g.ou(this.element,!0);g.G(this,a);a.subscribe("dragstart",this.HL,this);a.subscribe("dragmove",this.GL,this);a.subscribe("dragend",this.FL,this);this.Wa=this.Va=0;b="";this.i.windowOpacity&&(a=x2(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.i.windowOpacity+
")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":zIa[this.i.textAlign]};this.Za&&(a["border-radius"]=b?this.Na/8+"px":"");if(this.u=2===this.l.params.vf||3===this.l.params.vf)b=this.element,c="vertical-rl",1===this.i.CC&&(c="vertical-lr"),g.xe&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.ig(b,"-o-writing-mode",c),g.ig(b,"-webkit-writing-mode",c),g.ig(b,"writing-mode",c),g.ig(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3===this.l.params.vf&&(g.ig(b,"text-orientation",
""),g.ig(b,"transform","rotate(180deg)"));g.ig(this.element,a);switch(this.i.uh){case 0:case 1:case 2:g.K(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},yIa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},AIa=function(a,b){var c={},d=b.background?b.background:a.i.Yc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.Yc.backgroundOpacity;d=x2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Za&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Na/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ea*yIa(b)+"px";d=1;e=b.color||a.i.Yc.color;if(b.color||null!=b.textOpacity)e=x2(e),d=null==b.textOpacity?a.i.Yc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.Cz&&(h=e=b.Cz);var l=a.Ea/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.yq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.Yc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.oi&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.mO&&(c.visibility="hidden");1===b.BG&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.fE||g.Hs,3===a.l.params.vf?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Ni||2===b.Ni||3===b.Ni||4===b.Ni||5===b.Ni)if(g.fE)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Ni){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},BIa=function(a){a.G=g.Ee("SPAN");
g.ig(a.G,{display:"block"});g.K(a.G,"caption-visual-line");a.B.appendChild(a.G)},CIa=function(a,b){var c=g.Ee("SPAN");
g.ig(c,{display:"inline-block","white-space":"pre-wrap"});g.ig(c,AIa(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.ig(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ig(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},DIa=function(a,b,c){a.ma=a.ma||!!c;
var d={};g.Qa(d,a.i.Yc);g.Qa(d,c||b.i);g.Qa(d,a.ob.Yc);(c=!a.G)&&BIa(a);for(var e=a.ra&&a.xa&&g.Rb(d,a.xa)?a.ra:CIa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(BIa(a),e=CIa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Fe(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.fE||!g.mg(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.mg(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),
g.ze?g.ig(e,m,"1em"):g.ig(e,m,"0.5em")))}a.xa=d;a.ra=e;a.C.push(b)},z2=function(a,b,c){g.hM.call(this,a);
this.videoData=b;this.audioTrack=c;this.B=b.ez},A2=function(a,b,c,d,e,f,h){y2.call(this,a,b,c,d,e,f,h);
this.type=1},B2=function(a,b,c,d,e,f,h){y2.call(this,a,b,c,d,e,f,h);
this.type=2;this.J=[];this.W=this.L=this.Da=0;this.Y=NaN;this.Ya=0;this.jb=null;this.Fa=new g.J(this.jR,433,this);g.K(this.element,"ytp-caption-window-rollup");g.G(this,this.Fa);g.ig(this.element,"overflow","hidden")},EIa=function(a,b){if(!b)return"";
a.u&&1!==a.l.params.CC&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},FIa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.l.params.al,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.L=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.i.Gl)?(e=g.Ee("SPAN"),g.Me(e,"\u2013".repeat(d)),g.ig(e,AIa(a,a.i.Yc)),a.B.appendChild(e),a.Y=e.offsetWidth,a.B.removeChild(e)):a.Y=0);d=a.B;a.W=c.call(b,a.Y,a.Ya,(a.u?d.offsetHeight:d.offsetWidth)+1)},GIa=function(a,b){FIa(a);
var c=a.J.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.L-c;if(c!==a.Da){var d=0<c&&0===a.Da;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.on(a.Fa));g.ig(a.B,"transform",EIa(a,c));a.Da=c}FIa(a)},C2=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.Vv.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},D2=function(a,b,c,d,e){g.Vv.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},HIa=function(a){var b="_"+E2++;
return new D2(0,0x8000000000000,0,b,a)},JIa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Gd){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=IIa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new C2(a,b,e,c,l,d,m)}switch(m.Gd){case 9:case 10:m.Ni=1;break;case 11:m.Ni=2;break;case 12:m.Ni=3;break;case 13:m.Ni=4;break;case 14:m.Ni=5}return new C2(a,b,e,c,l.textContent||"",d,m)},IIa=function(a,b,c,d,e){var f=g.yq(),h=
f?g.Ee("DIV"):g.Ee("RUBY"),l=g.Ee("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ee("DIV"):g.Ee("RP");a.textContent=b;h.appendChild(a);b=f?g.Ee("DIV"):g.Ee("RT");b.textContent=c;h.appendChild(b);c=e.Gd;if(10===c||11===c||12===c||13===c||14===c)if(g.ig(b,"text-emphasis-style","filled circle"),g.ig(b,"text-emphasis-color","currentcolor"),g.ig(b,"webkit-text-emphasis","filled circle"),11===e.Gd||13===e.Gd)g.ig(b,"webkit-text-emphasis-position","under left"),g.ig(b,"text-emphasis-position","under left");c=!0;if(4===e.Gd||7===e.Gd||12===e.Gd||
14===e.Gd)g.ig(h,"ruby-position","over"),g.ig(h,"-webkit-ruby-position","before");else if(5===e.Gd||6===e.Gd||11===e.Gd||13===e.Gd)g.ig(h,"ruby-position","under"),g.ig(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ee("DIV"):g.Ee("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.ig(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.ig(f,"display","none"),f=f.nextElementSibling,g.ig(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ig(h.lastElementChild,"display","none"),d?(g.ig(h,"padding-top","0.6em"),g.ig(f,"top","0")):(g.ig(h,"padding-bottom","0.6em"),g.ig(f,"bottom","0")));return h},F2=function(){g.F.apply(this,arguments)},G2=function(a){F2.call(this);
this.C=a;this.B={};this.V={};this.W={};this.G="_"+E2++;this.L={};this.u=this.i=null;this.J=!0},H2=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},I2=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},J2=function(a,b){a=H2(a,b);
return void 0!==a?a:null},L2=function(a,b){a=a.getAttribute(b);
if(null!=a)return K2.test(a),a},KIa=function(a,b){var c={},d=b.getAttribute("ws");
g.Qa(c,d?a.W[d]:a.C);a=J2(b,"mh");null!=a&&(c.tq=a);a=J2(b,"ju");null!=a&&(c.textAlign=a);a=J2(b,"pd");null!=a&&(c.vf=a);a=J2(b,"sd");null!=a&&(c.CC=a);a=L2(b,"wfc");null!=a&&(c.windowColor=a);b=H2(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},LIa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Qa(c,a.V[d]);a=J2(b,"ap");null!=a&&(c.uh=a);a=H2(b,"cc");null!=a&&(c.Gl=a);a=H2(b,"ah");null!=a&&(c.Dg=a);a=H2(b,"rc");null!=a&&(c.al=a);b=H2(b,"av");null!=b&&(c.Oi=b);return c},MIa=function(a,b,c,d){var e={};
g.Qa(e,LIa(a,b));g.Qa(e,KIa(a,b));d?g.Rb(e,a.C)?(d=a.G,e=a.C):d="_"+E2++:d=b.getAttribute("id")||"_"+E2++;a=H2(b,"t")+c;b=H2(b,"d")||0x8000000000000;if(2===e.vf||3===e.vf)c=e.al,e.al=e.Gl,e.Gl=c;return new D2(a,b,0,d,e)},M2=function(a){F2.call(this);
this.G=a;this.i=new Map;this.B=new Map;this.C=new Map;this.u=new Map},N2=function(a){a=g.ce(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},NIa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.al=a);b=b.ccColCount;void 0!==b&&(f.Gl=b);if(2===f.vf||3===f.vf)b=f.al,f.al=f.Gl,f.Gl=b;return new D2(c,d,0,e,f)},P2=function(){this.u=this.time=this.mode=this.l=0;
this.B=new O2(this);this.C=new O2(this);this.i=[];this.clear()},PIa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{zn:a,
Bl:b,result:0};a=OIa[a];b=OIa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Bl===d;if(d)return{zn:a,Bl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{zn:a,Bl:b,result:2};return{zn:a,Bl:b,result:3}},RIa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.u&&a.reset(),a.B.l.clear(),a.C.l.clear()):(a.u=0,QIa(a.B,b,c,d))},SIa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?RIa(a,d.nF,d.oF,b):1===d.type&&a.l&496&&QIa(a.C,d.nF,d.oF,b);a.i.length=0},Q2=function(){this.type=0},R2=function(){this.state=this.Bl=this.zn=0},TIa=function(){this.timestamp=this.i=0},S2=function(a){this.C=a;
this.u=[];this.i=this.l=this.row=0;this.style=new Q2;for(a=this.B=0;15>=a;a++){this.u[a]=[];for(var b=0;32>=b;b++)this.u[a][b]=new TIa}},T2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.u[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.u[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},YIa=function(a,b){switch(a){case 0:return UIa[(b&127)-32];
case 1:return VIa[b&15];case 2:return WIa[b&31];case 3:return XIa[b&31]}return 0},U2=function(a){return a.u[a.row][a.l]},V2=function(a,b,c){2<=b&&1<a.l&&(--a.l,U2(a).i=0);
var d=U2(a);d.timestamp=a.C.time+0;d.i=YIa(b,c);32>a.l&&a.l++},ZIa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.u[b+e][f],l=a.u[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},W2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.u[b+d][e].reset()},X2=function(a){a.row=0<a.i?a.i:1;
a.l=1;W2(a,0,15)},Y2=function(a){this.u=a;
this.C=0;this.style=new Q2;this.G=new S2(this.u);this.J=new S2(this.u);this.text=new S2(this.u);this.l=this.G;this.B=this.J;this.i=this.l},Z2=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(T2(d,c),X2(a.l),X2(a.B),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.u.mode=1<<d.B;e?d.l=1:d.i!==b&&(d.i>b?(T2(d,c),W2(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},$Ia=function(a){a.style.set(1);
a.i=a.B;a.i.i=0;a.i.style=a.style;a.u.mode=1<<a.i.B},aJa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.u.mode=1<<a.i.B},O2=function(a){this.i=a;
this.C=0;this.u=new Y2(this.i);this.G=new Y2(this.i);this.l=new R2;this.B=this.u},QIa=function(a,b,c,d){a.l.update();
b=PIa(b,c,a.l);switch(b.result){case 0:return;case 1:case 2:return}var e=b.zn;c=b.Bl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.i,b&96&&V2(a,0,b),c&96&&V2(a,0,c),0!==b&&0!==c&&3===a.style.type&&T2(a,d));else if(e&16)a:if(!a.l.matches(e,c)&&(b=a.l,b.zn=e,b.Bl=c,b.state=2,b=e&8?a.G:a.u,a.B=b,a.i.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;ZIa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));W2(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:V2(b.i,0,32);break a;case 48:57===c?(d=b.i,U2(d).i=0,32>d.l&&d.l++):V2(b.i,1,c&15)}break;case 2:c&32&&V2(b.i,2,c&31);break;case 3:c&32&&V2(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:$Ia(b);
break;case 33:d=b.i;1<d.l&&(--d.l,U2(d).i=0);break;case 36:d=b.i;b=U2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.u[a][c]===b){for(;32>=c;c++)d.u[a][c].reset();break}break;case 37:Z2(b,2,d);break;case 38:Z2(b,3,d);break;case 39:Z2(b,4,d);break;case 40:V2(b.i,0,32);break;case 41:b.style.set(2);b.i=b.l;b.i.i=0;b.i.style=b.style;b.u.mode=1<<b.i.B;break;case 42:d=b.text;d.i=15;d.style.set(4);X2(d);aJa(b);break;case 43:aJa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:T2(a,d)}W2(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;T2(a,d);ZIa(a,b,b+1,a.i-1);W2(a,a.row,1)}break;case 46:W2(b.B,0,15);break;case 47:T2(b.l,d),b.B.updateTime(b.u.time+0),d=b.B,b.B=b.l,b.l=d,$Ia(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.l+=c&3)&&(d.l=32)}}},bJa=function(){},$2=function(a,b,c){this.trackData=a;
this.G=c;this.version=this.C=this.u=this.byteOffset=0;this.i=new DataView(this.trackData);this.l=[]},a3=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.i.getUint8(b)},b3=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.i.getUint32(b)},c3=function(a,b){F2.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.i=new P2;this.i.l=1<<this.track},d3=function(a){if("string"===typeof a)return!1;
a=new $2(a,8,0);return cJa(a)},cJa=function(a){if(!(a.byteOffset<a.i.byteLength)||1380139777!==b3(a))return!1;
a.version=a3(a);if(1<a.version)return!1;a3(a);a3(a);a3(a);return!0},e3=function(){F2.call(this)},dJa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.oi=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new C2(b,c,d,e.id,p.nodeValue,f||0<n,g.Ob(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};g.Qa(r,l);dJa(a,b,c,d,e,!0,p,r,m)}}},f3=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},eJa=function(a,b,c,d){d=Object.assign({tq:0},d);
return new D2(a,b,c,"_"+E2++,d)},g3=function(a){g.F.call(this);
this.l=a;this.i=null},fJa=function(a,b){if("string"===typeof b||d3(b))return b;
var c=new DataView(b);if(8>=c.byteLength||1718909296!==c.getUint32(4))return"";c=g.$y(c,0,1835295092);if(!c||!c.size)return"";a=a.l.Z("html5_fix_mdat_offset_killswitch")?b.slice(c.dataOffset,c.dataOffset+c.size):b.slice(c.dataOffset,c.offset+c.size);return g.Ye(new Uint8Array(a))},hJa=function(a){var b={};
if(a=g.JE(a))b.lang=a,gJa.test(a)&&(b.vf=1);return b},j3=function(a){g.eM.call(this,a);
var b=this;this.I=a;this.i=this.I.T();this.videoData=this.I.getVideoData();this.Ya=this.I.Xa();this.B={Yc:{}};this.C={Yc:{}};this.Y=[];this.V={};this.Da={};this.W=!1;this.jb=g.uG(this.videoData);this.Va=g.Roa(this.videoData,this.I);this.Za=!!this.videoData.captionTracks.length;this.ob=!!this.videoData.Yb;this.Ta="3"===this.i.controlsType;this.u=this.J=this.L=this.Ea=this.Na=null;this.Fa=new g3(this.i);this.l=null;this.xa=new g.UL(this);this.Ma=new g.V({D:"div",K:"ytp-caption-window-container",U:{id:"ytp-caption-window-container"}});
var c=null,d=g.po("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Rn(d));this.storage=c;c=a.md();d=!(null===c||void 0===c||!c.Wt());this.Wa=!(null===c||void 0===c||!c.Xt());this.G=this.Ta&&d&&!this.Va;this.ra=!this.G&&this.Ta&&this.Wa&&this.Va;g.G(this,this.Fa);this.G?this.Aa=this.ma=null:(this.ma=new g.kn(this.TC,void 0,this),g.G(this,this.ma),this.Aa=new g.J(this.xS,2E3,this),g.G(this,this.Aa));g.G(this,this.xa);this.i.Z("caption_window_container_killswitch")||g.HL(this.player,this.Ma.element,
4);g.G(this,this.Ma);this.G||this.xa.N(a,"resize",this.VC);this.xa.N(a,"onPlaybackAudioChange",this.xP);this.xa.N(a,g.Yv("captions"),function(e){b.rd(e)});
this.xa.N(a,g.Zv("captions"),function(e){b.Re(e)});
h3(this,i3(this,"display-settings")||{})},iJa=function(a){if(1===a.i.Fa||1===a.videoData.pp||"alwayson"===g.eG(a.videoData,"yt:cc"))return!0;
if(2===a.i.Fa){var b;g.eE(a.i)?b=(0,g.dM)():b=i3(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().l;b=s2(a.player.getAudioTrack(),t2(a.i));var d=g.eG(a.videoData,"yt:cc");if(void 0===k3(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.eG(a.videoData,"yt:cc")},l3=function(a,b){if(a.l&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.l},k3=function(a){var b=void 0,c=g.vr(g.tr.getInstance(),65);
if(g.eE(a.i)&&null!=c){if(null!=(0,g.dM)())return!1;b=!c}return b},jJa=function(a){var b;
a.jb?b=new z2(a.i,a.videoData,a.player.getAudioTrack(),a.player):a.Va?b=new w2(a.videoData.i,a.player):a.Za?b=new g.iM(a.i,a.videoData,a.player.getAudioTrack()):b=new g.kM(a.videoData.Yb,a.videoData.videoId,g.gja(a.videoData),a.videoData.qk,a.i);return b},n3=function(a,b){if(a.u){if(a.J&&a.J.B)return a.J.B;
b||(b=a.ob?!1:a.Za?!1:!0);b=g.fM(a.u.l,b);for(var c=[a.videoData.captionsLanguagePreference,a.i.captionsLanguagePreference,g.eG(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.JE(b[e])===c[d])return b[e];return a.J&&a.J.u?a.J.u:(c=b.find(function(f){return f.isDefault}))?c:b[0]||m3(a)}return null},m3=function(a){return a.J&&a.J.i},o3=function(a){var b=m3(a);
return!!b&&a.l===b},kJa=function(a,b){var c=a.I.md().ke().textTracks;
a=a.l.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},q3=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.W=c,a.W&&(g.eE(a.i)?(0,g.K0)(!!b):p3(a,"module-enabled",!!b)));a.l=b;l3(a)&&(a.l=m3(a));a.load()},lJa=function(a,b){a.i.Z("caption_window_container_killswitch")?g.HL(a.player,b,4):a.Ma.element.appendChild(b)},mJa=function(a,b){var c=a.Ya.getVideoContentRect(!0).height;
if(!c)return null;var d=a.l?g.JE(a.l):null;d&&gJa.test(d)&&(b.params.vf=1);d=a.Ya.getPlayerSize();switch(null!=b.params.tq?b.params.tq:1<b.i.length?1:0){case 1:return new A2(b,a.B,a.C,c,d.width,d.height,a.i.experiments);case 2:return new B2(b,a.B,a.C,c,d.width,d.height,a.i.experiments);default:return new y2(b,a.B,a.C,c,d.width,d.height,a.i.experiments)}},h3=function(a,b,c){c=void 0===c?!1:c;
var d=r3.Yc;a.B={};g.Qa(a.B,r3);a.B.Yc={};g.Qa(a.B.Yc,d);a.C={Yc:{}};var e=b.backgroundOverride?a.C:a.B,f=b.background||d.background;K2.test(f);e.Yc.background=f;e=b.colorOverride?a.C:a.B;f=b.color||d.color;K2.test(f);e.Yc.color=f;e=b.windowColorOverride?a.C:a.B;f=b.windowColor||r3.windowColor;K2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Yc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Yc.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.oi?3:d.bold?1:d.oi?2:0);f=f.Yc;switch(e){case 1:f.bold=!0;delete f.oi;break;case 2:delete f.bold;f.oi=!0;break;case 3:f.bold=!0;f.oi=!0;break;default:delete f.bold,delete f.oi}e=b.textOpacityOverride?a.C:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Yc.textOpacity=f;e=b.windowOpacityOverride?a.C:a.B;f=b.windowOpacity;null==f&&(f=r3.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Yc.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Yc.fontFamily=f;a.loaded&&a.VC();c&&p3(a,"display-settings",b)},oJa=function(a,b){b&&!a.L?(b=HIa({vf:0,
lang:"en"}),a.L=[b,new C2(b.start,b.end-b.start,0,b.id,"Captions look like this")],a.player.xd(a.L)):!b&&a.L&&(nJa(a,a.L),a.L=null)},nJa=function(a,b){a.player.Gf(b);
g.zb(b,function(c){g.kb(this.Y,c)},a);
g.ln(a.ma)},i3=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},p3=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.TR.prototype.qs=g.ca(31,function(a){var b=2;this.Ea.has(a)?b=0:g.Rta(this,a)&&(b=1);return b});
g.jU.prototype.qs=g.ca(30,function(a){return this.i.qs(a)});
g.yM.prototype.Kr=g.ca(29,function(){this.ea();for(var a=g.qe(document,"track",void 0,this.i),b=0;b<a.length;b++)g.Ie(a[b])});
g.ER.prototype.Kr=g.ca(28,function(){this.i.Kr()});
g.yM.prototype.Xt=g.ca(27,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.ER.prototype.Xt=g.ca(26,function(){return this.i.Xt()});
g.yM.prototype.Wt=g.ca(25,function(){return!!this.i.textTracks});
g.ER.prototype.Wt=g.ca(24,function(){return this.i.Wt()});
g.yM.prototype.Br=g.ca(23,function(a){this.ea();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.ER.prototype.Br=g.ca(22,function(a){this.i.Br(a)});
g.hM.prototype.QB=g.ca(21,function(){return!1});
g.hM.prototype.mm=g.ca(20,function(){});
g.iM.prototype.mm=g.ca(19,function(a,b,c){var d=this;this.Ga();b=this.Vn(a,b);this.ll();this.i=g.vp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.kM.prototype.mm=g.ca(18,function(a,b,c){var d=this;this.Ga();b=this.Vn(a,b);this.ll();this.i=g.vp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.VT.prototype.Fs=g.ca(6,function(){return this.W});
g.uW.prototype.Fs=g.ca(5,function(){var a;return(null===(a=g.W(this))||void 0===a?void 0:a.zs())||null});
g.AL.prototype.zs=g.ca(4,function(){return this.app.Fs()});
g.UV.prototype.zs=g.ca(3,function(){var a;return(null===(a=this.l)||void 0===a?void 0:a.Fs())||null});
var gJa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,sIa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",
as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",
bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",
cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",
en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",
fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",
hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",
kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",
ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",
mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"Maori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian (Moldova)",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",
mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",
nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",
rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",
sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",
su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",
tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",
xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
u2.prototype.contains=function(a){a=g.ub(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
u2.prototype.length=function(){return this.segments.length/2};
g.v(v2,g.F);g.k=v2.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.l&&this.l.cancel()};
g.k.AD=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Lc();var b=this.i;this.i=g.ab(this.W.Wl(a).i);b!==this.i&&this.V&&this.V()};
g.k.reset=function(){this.B=new u2;this.l&&(this.l.cancel(),this.l=null)};
g.k.hH=function(){var a;this.Ga();var b;if(b=null!=this.i)b=this.i,b=b.i.ul(b);if(b&&!this.l&&!(this.i&&30<this.i.startTime-this.player.getCurrentTime())){b=this.i;b=b.i.Xq(b);if(this.J.Z("enable_h5_ssdai_caption")&&(null===(a=this.player.getVideoData())||void 0===a?0:a.enableServerStitchedDai)){var c=this.player.zs();if(c){var d=b.i[0].Ia,e=c.Fv(b.i[0].C,d,b.i[0].i.info.id,!0);if(e)if(c=c.qs(d),0===c)b.B=e;else if(2===c)return}}b.i[0].duration?(this.B.contains(b.i[0].Ia)||rIa(this,b),this.i=g.ab(b.i)):
!g.R(this.J.experiments,"force_caption_seek_for_live_killswitch")&&this.i&&this.i.B&&this.i.B+this.player.Lc()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime())}this.L.start()};
g.v(w2,g.hM);g.k=w2.prototype;g.k.mm=function(a,b,c){var d=this;this.ll();b=uIa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?vIa(this,b,"386"):vIa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber()));this.u=new v2(new g.Poa,this.I,b,function(f,h){c(f,a,h,e)},this.G||g.MA(b.info),function(){d.u&&d.u.reset();
d.C=!0})}};
g.k.QB=function(){var a=this.C;this.C=!1;return a};
g.k.nq=function(a){var b=this.G?[new g.GE({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.GE({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?tIa(this,"386"):tIa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g.gM(this.l,c.value);a()};
g.k.ll=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.Vn=function(){return""};
var K2=/^#(?:[0-9a-f]{3}){1,2}$/i,xIa=/#(.)(.)(.)/,wIa=/^#(?:[0-9a-f]{3}){1,2}$/i;var zIa=["left","right","center","justify"];g.v(y2,g.V);g.k=y2.prototype;g.k.HL=function(a,b){var c=g.wg(this.element,this.element.parentElement);this.Va=a-c.x;this.Wa=b-c.y;g.K(this.element,"ytp-dragging")};
g.k.GL=function(a,b){var c=g.yg(this.element);a=a-this.Va-.02*this.playerWidth;var d=b-this.Wa-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.ce(e,0,2));var f=(d+c.height/2)/this.Ma*3;f=Math.floor(g.ce(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.ce(a,0,1);c=(d+f/2*c.height)/this.Ma;c=100*g.ce(c,0,1);this.l.params.uh=b;this.l.params.Oi=c;this.l.params.Dg=a;this.i.uh=b;this.i.Oi=c;this.i.Dg=a;this.Aa.uh=b;this.Aa.Oi=c;this.Aa.Dg=a;this.bJ()};
g.k.FL=function(){g.yn(this.element,"ytp-dragging")};
g.k.bJ=function(){this.Fq(this.C)};
g.k.Vb=function(){return this.type};
g.k.Fq=function(a){var b=Math.min(this.fG(),this.maxWidth),c=this.eG(),d="";3===this.l.params.vf&&(d="rotate(180deg)");g.ig(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.oz(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.Dg+2;d=this.i.uh;switch(d){case 0:case 3:case 6:(b=this.i.Yc.fontSizeIncrement)&&0<b&&2!==this.i.vf&&3!==
this.i.vf&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Oi+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ig(this.element,
a)};
g.k.oz=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.ma||this.C.length>b)b=0,this.ma=!1,this.C=[],this.G=this.xa=this.ra=null,g.Ge(this.B);for(;b<a.length;b++)DIa(this,a[b])};
g.k.fG=function(){return 0};
g.k.eG=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.v(z2,g.hM);z2.prototype.mm=function(a,b,c){pIa(this.videoData.videoId,a.vssId,c)};
z2.prototype.nq=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.gM(this.l,c.value);a()};g.v(A2,y2);A2.prototype.oz=function(a){var b=this.l.i;y2.prototype.oz.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};g.Qa(d,c.i);g.Qa(d,pJa);var e=c.i;var f=d}DIa(this,c,d)}};
var pJa={mO:!0};g.v(B2,y2);g.k=B2.prototype;g.k.bJ=function(){g.pn(this.Fa)};
g.k.jR=function(){g.yn(this.element,"ytp-rollup-mode");this.Fq(this.jb,!0)};
g.k.eG=function(){return this.u?this.W:this.L};
g.k.fG=function(){return this.u?this.L:this.W};
g.k.Fq=function(a,b){this.jb=a;if(this.l.params.al){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.Ya=this.W;this.L=this.W=0;y2.prototype.Fq.call(this,a);GIa(this,b)}y2.prototype.Fq.call(this,a)};g.v(C2,g.Vv);C2.prototype.toString=function(){return g.Vv.prototype.toString.call(this)};g.v(D2,g.Vv);D2.prototype.toString=function(){return g.Vv.prototype.toString.call(this)};
var E2=0;g.v(F2,g.F);F2.prototype.l=function(){return[]};
F2.prototype.reset=function(){};g.v(G2,F2);G2.prototype.reset=function(){this.L={};this.u=this.i=null;this.J=!0};
G2.prototype.l=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.q(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.B,h={},l=a.getAttribute("p");l&&g.Qa(h,this.B[l]);l=I2(a,"b");null!=l&&(h.bold=
l);l=I2(a,"i");null!=l&&(h.oi=l);l=I2(a,"u");null!=l&&(h.underline=l);l=J2(a,"et");null!=l&&(h.charEdgeStyle=l);l=J2(a,"of");null!=l&&(h.offset=l);l=L2(a,"bc");null!=l&&(h.background=l);l=L2(a,"ec");null!=l&&(h.Cz=l);l=L2(a,"fc");null!=l&&(h.color=l);l=J2(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=H2(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=H2(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=H2(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=J2(a,"rb");null!=l&&10!==l&&0!==l&&(h.Gd=10<l?l-
1:l);a=J2(a,"hg");null!=a&&(h.BG=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.W[c]=KIa(this,a);break;case "wp":c=a.getAttribute("id"),this.V[c]=LIa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.q(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=MIa(this,a,b,!1);(a=this.L[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.L[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.G;h=!!I2(a,"a");l=(H2(a,
"t")||0)+l;var m=H2(a,"d")||5E3;h||(!this.J&&this.u&&this.u.windowId===f&&this.u.end>l&&(this.u.end=l),this.u&&"\n"===this.u.text&&(this.u.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.B[p]:null;var r=Array.from(a.childNodes);r.length&&(this.J=null!=a.getAttribute("d"));for(var t=0;t<r.length;t++){var u=r[t],x=void 0;0<t&&(h=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.B[u]:null)&&u.Gd&&(1===u.Gd?(u=r.slice(t,t+4),4===u.length&&(x=JIa(l,m,
f,h,n,u,this.B),t+=3)):x=JIa(l,m,f,h,n,[y],this.B)),!x){var A=y;x=l;y=m;u=f;var E=h,I=n,H=A.textContent?A.textContent:"",U=A.getAttribute("p");U=U?this.B[U]:null;A=H2(A,"t")||0;x=new C2(x+A,y-A,I,u,H,E,U)}}else x=new C2(l,m,n,f,u.textContent||"",h,p);c.push(x);this.u=x}if(0<c.length)for(c[0].windowId===this.G&&(this.i=MIa(this,a,b,!0),d.push(this.i)),a=g.q(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var qJa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(M2,F2);M2.prototype.reset=function(){this.u.clear()};
M2.prototype.l=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.q(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.oi=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.Cz=N2(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=N2(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=N2(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Gd=10<h?h-1:h,f.Ni=qJa.get(f.Gd));e.hgHorizGroup&&(f.BG=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.q(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.C.get(h)):Object.assign(f,
this.G),void 0!==e.mhModeHint&&(f.tq=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.vf=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.CC=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=N2(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.C.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.q(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.B.get(h)),void 0!==e.ahHorPos&&
(f.Dg=e.ahHorPos),void 0!==e.apPoint&&(f.uh=e.apPoint),void 0!==e.avVerPos&&(f.Oi=e.avVerPos),void 0!==e.ccCols&&(f.Gl=e.ccCols),void 0!==e.rcRows&&(f.al=e.rcRows),this.B.set(a++,f);if(c.events){a=[];c=g.q(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=NIa(this,l,d,e,f),a.push(d),this.u.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+E2++,h=NIa(this,l,d,e,f),a.push(h),this.u.set(f,h));0===e&&(e=5E3);h=this.u.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,r=null;l.pPenId&&(r=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.tq?h.params.tq:1<h.i.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.Gd)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var A=p[t+1].pPenId;(A=this.i.get(A))&&A.Gd&&2===A.Gd?(A=p[t+2].pPenId,A=this.i.get(A),!A||!A.Gd||3>A.Gd?t=!1:(A=p[t+3].pPenId,t=(A=this.i.get(A))&&
A.Gd&&2===A.Gd?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;A=p[l+2].utf8;var E=this.i.get(p[l+2].pPenId);u=IIa(u,x,A,t,E);m=new C2(d,e,n,f,u,m,y);l+=3}else m=new C2(d+x,e-x,n,h.id,u,m,y||r);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};P2.prototype.clear=function(){this.u=this.time=this.mode=0;this.i=[];this.reset()};
P2.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var OIa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Q2.prototype.set=function(a){this.type=a};
Q2.prototype.get=function(){return this.type};
R2.prototype.clear=function(){this.state=0};
R2.prototype.update=function(){this.state=2===this.state?1:0};
R2.prototype.isValid=function(){return 0!==this.state};
R2.prototype.matches=function(a,b){return this.isValid()&&a===this.zn&&b===this.Bl};
TIa.prototype.reset=function(){this.timestamp=this.i=0};
S2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.u[b][c].timestamp=a};
S2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.u[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
S2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.u[b][c].reset();this.B=a;this.i=0;this.l=this.row=1};
var UIa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],VIa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],WIa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],XIa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Y2.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.l=this.G;this.B=this.J;this.i=this.l;var c=(a<<2)+(b<<1);this.G.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
O2.prototype.reset=function(a){this.C=a;this.l.clear();this.B=this.u;this.u.reset(a,0);this.G.reset(a,1)};bJa.prototype.B=function(){};g.v($2,bJa);$2.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+E2++;c=c/1E3-this.G;d=d/1E3-this.G;a=new D2(c,d-c,5,f,{textAlign:0,uh:0,Dg:2.5*b,Oi:5.33*a});e=new C2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.v(c3,F2);c3.prototype.l=function(a){a=new $2(a,a.byteLength,this.u);if(cJa(a)){for(;a.byteOffset<a.i.byteLength;)for(0===a.version?a.u=b3(a)*(1E3/45):1===a.version&&(a.u=4294967296*b3(a)+b3(a)),a.C=a3(a);0<a.C;a.C--){var b=a3(a),c=a3(a),d=a3(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.u,type:this.track,nF:c,oF:d,order:b.i.length}))}SIa(this.i,a);return a.l}return[]};
c3.prototype.reset=function(){this.i.clear()};g.v(e3,F2);
e3.prototype.l=function(a,b){var c=[];a=a.split(rJa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!sJa.test(e)){var h=s3.exec(e);if(h&&4<=h.length){var l=f3(h[1]),m=f3(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var r="";var t=null,u="";n=g.q(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.Oi=Number.parseInt(p,10),2===x.length&&(r=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.Dg=Number.parseInt(t,10);2===x.length&&(u=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||r||(r="end");if(!t)switch(h.textAlign){case 0:h.Dg=0;break;case 1:h.Dg=100;break;case 2:h.Dg=50}if(null!=h.textAlign){p=0;switch(r){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}r=0>p||8<p?7:p;h.uh=r}e=e.substring(s3.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=eJa(l,m,5,u),m=new C2(l,m,5,f.id,h,!1,g.Ob(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(r=h.split(tJa),1===r.length?(h=5,u=eJa(l,m,h,u)):(p=h=6,u=Object.assign({Gl:32},u),u=new D2(l,m,p,"_"+E2++,u)),c.push(u),p=l,t=0;t<r.length;t++)n=r[t],0===t%2?(x=g.a0("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,dJa(this,p,m-(p-l),h,u,0<t,y,e,c)):p=f3(n)+f}s3.lastIndex=0}}return c};
var sJa=/^NOTE/,rJa=/(?:\r\n|\r|\n){2,}/,s3=/^((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})[\t ]+--\x3e[\t ]+((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})(?:[\t ]*)(.*)(?:\r\n|\r|\n)/gm,tJa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.HR.Zv(e3,{l:"wvppt"});g.v(g3,g.F);g3.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
g3.prototype.reset=function(){this.i&&this.i.reset()};
g3.prototype.va=function(){g.F.prototype.va.call(this);this.clear()};var r3={windowColor:"#080808",windowOpacity:0,textAlign:2,uh:7,Dg:50,Oi:100,Yc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(j3,g.eM);g.k=j3.prototype;g.k.va=function(){if(this.G||this.ra){var a=this.I.md();a&&!a.Ga()&&a.Kr()}else oJa(this,!1);g.eM.prototype.va.call(this)};
g.k.Uo=function(){if(this.Ta)return this.G||this.ra;var a=s2(this.player.getAudioTrack(),t2(this.i));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?l3(this):k3(this)||l3(this)?!0:iJa(this)};
g.k.load=function(){var a=this;g.eM.prototype.load.call(this);var b=!g.R(this.i.experiments,"web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();this.u?(this.l&&(this.Fa.clear(),this.G?kJa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.mm(this.l,"json3",function(c,d,e,f){if(c){a.u.QB()&&(a.Y=[],a.I.Te("captions"),g.ln(a.ma),a.Fa.reset());var h=a.Fa;e=e||0;f=f||0;if(h.l.Z("html5_disable_rawcc_killswitch")){if("string"!==typeof c){var l=new DataView(c);
8<=l.byteLength&&1718909296===l.getUint32(4)&&(l=g.$y(l,0,1835295092),c=h.l.Z("html5_fix_mdat_offset_killswitch")?c.slice(l.dataOffset,l.dataOffset+l.size):c.slice(l.dataOffset,l.offset+l.size),d3(c)||(c=g.Ye(new Uint8Array(c))))}}else c=fJa(h,c);if(c)try{if("string"!==typeof c){var m=c,n=e,p=f;if(!d3(m))throw Error("Invalid binary caption track data");h.i||(h.i=new c3(p,d));var r=h.i.l(m,n)}else{if("WEBVTT"===c.substring(0,6))d=c,p=e,h.i||(h.i=new e3),n=h.i.l(d,p),.01>Math.random()&&g.Ru(Error("Deprecated subtitles format in web player: WebVTT")),
m=n;else b:{n=c;if("{"===n[0])try{h.i||(h.i=new M2(hJa(d)));m=h.i.l(n,e);break b}catch(E){g.Qu(E);m=[];break b}p=g.a0(n);if(!p||!p.firstChild){var t=Error("Invalid caption track data");t.params=n;throw t;}if("timedtext"===p.firstChild.tagName){if(3===Number(p.firstChild.getAttribute("format"))){h.i||(h.i=new G2(hJa(d),h.l));m=h.i.l(p,e);break b}var u=Error("Unsupported subtitles format in web player (Format2)");u.params=n;throw u;}if("transcript"===p.firstChild.tagName){var x=Error("Unsupported subtitles format in web player (Format1)");
x.params=n;throw x;}var y=Error("Invalid caption track data");y.params=n;throw y;}r=m}var A=r}catch(E){g.Qu(E),h.clear(),A=[]}else A=[];a.player.xd(A);!a.W||a.ra||o3(a)||g.ND(a.i)||g.DD(a.i)||(g.qn(a.Aa),A=HIa({uh:0,Dg:5,Oi:5,al:2,textAlign:0,vf:0,lang:"en"}),a.Ea=[A],h=["Click "," for settings"],a.Na||(r=new g.MJ(g.bK()),g.G(a,r),a.Na=r.element),r=A.end-A.start,(d=g.HE(a.l))&&a.Ea.push(new C2(A.start,r,0,A.id,d)),a.Ea.push(new C2(A.start,r,0,A.id,h[0]),new C2(A.start,r,0,A.id,a.Na,!0),new C2(A.start,
r,0,A.id,h[1],!0)),a.player.xd(a.Ea),g.on(a.Aa));!a.W||a.ra||o3(a)||(g.eE(a.i)?(0,g.K0)(!0):p3(a,"module-enabled",!0),a.J&&(a.J.B=a.l),a.player.gp());a.W=!1}}),!b||this.G||this.ra||o3(this)||this.player.La("captionschanged",g.IE(this.l))),b||(this.l&&!o3(this)?this.player.La("captionschanged",g.IE(this.l)):this.player.La("onCaptionsTrackListChanged"))):(this.u=jJa(this),g.G(this,this.u),this.u.nq(function(){var c=s2(a.player.getAudioTrack(),t2(a.i)),d;
"CAPTIONS_INITIAL_STATE_UNKNOWN"===c?k3(a)||a.W||iJa(a)?d=n3(a,a.W):l3(a)&&(d=m3(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===c?d=n3(a,a.W):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===c&&l3(a)&&(d=m3(a));if(a.G||a.ra){var e=g.fM(a.u.l,!0);c=[];for(var f=0;f<e.length;f++){var h=e[f],l=g.Ee("TRACK");l.setAttribute("kind","subtitles");l.setAttribute("label",g.HE(h));l.setAttribute("srclang",g.JE(h));l.setAttribute("id",h.toString());a.ra||l.setAttribute("src",a.u.Vn(h,"vtt"));h===d&&l.setAttribute("default",
"1");c.push(l)}d=a.I.md();d.Br(c);d=d.ke();a.Wa&&a.xa.N(d.textTracks,"change",a.NR)}else!a.l&&d&&q3(a,d),a.player.La("onCaptionsTrackListChanged"),a.player.La("onApiChange")}))};
g.k.unload=function(){this.G&&this.l?kJa(this,!1):(this.Aa&&g.qn(this.Aa),this.player.Te("captions"),this.Y=[],this.u&&this.u.ll(),this.Fa.clear(),this.L&&this.player.xd(this.L),this.VC());g.eM.prototype.unload.call(this);this.player.gp();this.player.La("captionschanged",{})};
g.k.create=function(){this.Uo()&&this.load()};
g.k.NR=function(){for(var a=this.I.md().ke().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.fM(this.u.l,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.l:null)!==b&&q3(this,b,!0)};
g.k.nT=function(){!this.l&&this.G||this.unload()};
g.k.rd=function(a){this.Y.push(a);g.ln(this.ma)};
g.k.Re=function(a){g.kb(this.Y,a);this.u instanceof w2&&this.u.G&&this.player.Gf([a]);g.ln(this.ma)};
g.k.rS=function(a){if(a instanceof D2){var b=this.V[a.id];b&&b.l!==a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=mJa(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.Da[b]||(this.Da[b]=[]),this.Da[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Ma.element.id};
g.k.xS=function(){nJa(this,this.Ea);this.Ea=null};
g.k.TC=function(){var a=this;this.ma.stop();g.Pb(this.Da);this.Y.sort(g.Xv);var b=this.Y;if(this.L){var c=g.Je(b,function(d){return-1===this.L.indexOf(d)},this);
c.length&&(b=c)}g.zb(b,this.rS,this);g.Bb(this.V,function(d,e){a.Da[e]?(d.element.parentNode||(d instanceof B2||d instanceof A2||g.Eb(a.V,function(f,h){h!==e&&f.l.params.uh===d.l.params.uh&&f.l.params.Dg===d.l.params.Dg&&f.l.params.Oi===d.l.params.Oi&&(f.dispose(),delete a.V[h]);return h===e},a),lJa(a,d.element)),d.Fq(a.Da[e])):(d.dispose(),delete a.V[e])},this)};
g.k.BS=function(){h3(this,{},!0);g.R(this.i.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.La("captionssettingschanged")};
g.k.LN=function(){var a=r3.Yc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.oi?3:a.bold?1:a.oi?2:0,textOpacity:a.textOpacity,windowColor:r3.windowColor,windowOpacity:r3.windowOpacity};var b=i3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.UJ=function(a,b){var c={};g.Qa(c,i3(this,"display-settings"));g.Qa(c,a);h3(this,c,b);this.player.La("captionssettingschanged")};
g.k.VC=function(){!this.G&&this.loaded&&(g.Bb(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.TC())};
g.k.Je=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ce(b,-2,4);this.UJ({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&q3(this,this.l,!0);break;case "stickyLoading":void 0!==b&&this.i.u&&(g.eE(this.i)?(0,g.K0)(!!b):p3(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.G)break;if(!g.Ma(b))break;if(g.Ob(b)){q3(this,null,!0);break}a=g.fM(this.u.l,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?oIa(e,b.translationLanguage):e)}!c||c===this.l&&this.loaded||(b=(0,g.Goa)(),a=g.JE(c),b.length&&a===b[b.length-1]||(b.push(a),(0,g.lGa)(b)),q3(this,c,!0))}else return this.loaded&&this.l&&!o3(this)?g.IE(this.l):{};return"";case "tracklist":return this.u?g.Mc(g.fM(this.u.l,!(!b||!b.includeAsr)),function(f){return g.IE(f)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.G||void 0===b||oJa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.i.u&&a.push("stickyLoading");return a};
g.k.zA=function(){var a=this.l;return a?{cc:a.vssId}:{}};
g.k.bT=function(){this.loaded&&this.l&&!o3(this)?(g.eE(this.i)?(0,g.K0)(!1):p3(this,"module-enabled",!1),this.unload(),l3(this,!0)&&q3(this,m3(this),!1)):this.DJ()};
g.k.DJ=function(){this.loaded&&this.l||q3(this,o3(this)||!this.l?n3(this,!0):this.l,!0)};
g.k.xP=function(){var a=o3(this);l3(this,a)?q3(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Uo()&&(a?q3(this,n3(this),!1):this.load()))};
g.HR.Zv(j3,{TC:"smucd"});g.pM.captions=j3;})(_yt_player);
